name: birbal_db
services:
    db:
      image: postgres:latest
      environment:
        POSTGRES_USER: birbal
        POSTGRES_PASSWORD: akbar
        POSTGRES_DB: birbal_db
      ports:
      - "5432-5432" 
      restart: always